// Comprehensive JLPT Kanji Data
// N5: 80 kanji | N4: 166 kanji | N3: 367 kanji (representative) | N2: 367 (representative) | N1: 1017 (representative)

export type KanjiEntry = {
  char: string;
  meaning: string;
  onyomi: string[];
  kunyomi: string[];
  strokes: number;
  jlpt: string;
};

export const kanjiData: KanjiEntry[] = [
  // ══════════════════════════════════════════════════════════════════
  // N5 — 80 kanji
  // ══════════════════════════════════════════════════════════════════
  { char:"一", meaning:"satu", onyomi:["いち","いつ"], kunyomi:["ひと"], strokes:1, jlpt:"N5" },
  { char:"二", meaning:"dua", onyomi:["に"], kunyomi:["ふた"], strokes:2, jlpt:"N5" },
  { char:"三", meaning:"tiga", onyomi:["さん"], kunyomi:["み","みつ"], strokes:3, jlpt:"N5" },
  { char:"四", meaning:"empat", onyomi:["し"], kunyomi:["よ","よん"], strokes:5, jlpt:"N5" },
  { char:"五", meaning:"lima", onyomi:["ご"], kunyomi:["いつ"], strokes:4, jlpt:"N5" },
  { char:"六", meaning:"enam", onyomi:["ろく"], kunyomi:["む","むつ"], strokes:4, jlpt:"N5" },
  { char:"七", meaning:"tujuh", onyomi:["しち"], kunyomi:["なな"], strokes:2, jlpt:"N5" },
  { char:"八", meaning:"delapan", onyomi:["はち"], kunyomi:["や","やつ"], strokes:2, jlpt:"N5" },
  { char:"九", meaning:"sembilan", onyomi:["きゅう","く"], kunyomi:["ここの"], strokes:2, jlpt:"N5" },
  { char:"十", meaning:"sepuluh", onyomi:["じゅう"], kunyomi:["とお"], strokes:2, jlpt:"N5" },
  { char:"百", meaning:"seratus", onyomi:["ひゃく"], kunyomi:[], strokes:6, jlpt:"N5" },
  { char:"千", meaning:"seribu", onyomi:["せん"], kunyomi:["ち"], strokes:3, jlpt:"N5" },
  { char:"万", meaning:"sepuluh ribu", onyomi:["まん","ばん"], kunyomi:[], strokes:3, jlpt:"N5" },
  { char:"円", meaning:"yen / bulat", onyomi:["えん"], kunyomi:["まる"], strokes:4, jlpt:"N5" },
  { char:"年", meaning:"tahun", onyomi:["ねん"], kunyomi:["とし"], strokes:6, jlpt:"N5" },
  { char:"月", meaning:"bulan / rembulan", onyomi:["げつ","がつ"], kunyomi:["つき"], strokes:4, jlpt:"N5" },
  { char:"日", meaning:"hari / matahari", onyomi:["にち","じつ"], kunyomi:["ひ","か"], strokes:4, jlpt:"N5" },
  { char:"時", meaning:"waktu / jam", onyomi:["じ"], kunyomi:["とき"], strokes:10, jlpt:"N5" },
  { char:"分", meaning:"menit / bagian", onyomi:["ふん","ぶん"], kunyomi:["わ"], strokes:4, jlpt:"N5" },
  { char:"半", meaning:"setengah", onyomi:["はん"], kunyomi:["なか"], strokes:5, jlpt:"N5" },
  { char:"人", meaning:"orang", onyomi:["じん","にん"], kunyomi:["ひと"], strokes:2, jlpt:"N5" },
  { char:"山", meaning:"gunung", onyomi:["さん"], kunyomi:["やま"], strokes:3, jlpt:"N5" },
  { char:"川", meaning:"sungai", onyomi:["せん"], kunyomi:["かわ"], strokes:3, jlpt:"N5" },
  { char:"田", meaning:"sawah", onyomi:["でん"], kunyomi:["た"], strokes:5, jlpt:"N5" },
  { char:"木", meaning:"pohon / kayu", onyomi:["もく","ぼく"], kunyomi:["き"], strokes:4, jlpt:"N5" },
  { char:"火", meaning:"api", onyomi:["か"], kunyomi:["ひ"], strokes:4, jlpt:"N5" },
  { char:"水", meaning:"air", onyomi:["すい"], kunyomi:["みず"], strokes:4, jlpt:"N5" },
  { char:"金", meaning:"emas / uang", onyomi:["きん"], kunyomi:["かね"], strokes:8, jlpt:"N5" },
  { char:"土", meaning:"tanah", onyomi:["ど","と"], kunyomi:["つち"], strokes:3, jlpt:"N5" },
  { char:"大", meaning:"besar", onyomi:["だい","たい"], kunyomi:["おお"], strokes:3, jlpt:"N5" },
  { char:"小", meaning:"kecil", onyomi:["しょう"], kunyomi:["ちい","こ","お"], strokes:3, jlpt:"N5" },
  { char:"中", meaning:"tengah / dalam", onyomi:["ちゅう"], kunyomi:["なか"], strokes:4, jlpt:"N5" },
  { char:"上", meaning:"atas", onyomi:["じょう","しょう"], kunyomi:["うえ","のぼ"], strokes:3, jlpt:"N5" },
  { char:"下", meaning:"bawah", onyomi:["か","げ"], kunyomi:["した","くだ"], strokes:3, jlpt:"N5" },
  { char:"左", meaning:"kiri", onyomi:["さ"], kunyomi:["ひだり"], strokes:5, jlpt:"N5" },
  { char:"右", meaning:"kanan", onyomi:["う","ゆう"], kunyomi:["みぎ"], strokes:5, jlpt:"N5" },
  { char:"国", meaning:"negara", onyomi:["こく"], kunyomi:["くに"], strokes:8, jlpt:"N5" },
  { char:"語", meaning:"bahasa", onyomi:["ご"], kunyomi:["かた"], strokes:14, jlpt:"N5" },
  { char:"学", meaning:"belajar", onyomi:["がく"], kunyomi:["まな"], strokes:8, jlpt:"N5" },
  { char:"校", meaning:"sekolah", onyomi:["こう"], kunyomi:[], strokes:10, jlpt:"N5" },
  { char:"先", meaning:"sebelum / ahli", onyomi:["せん"], kunyomi:["さき"], strokes:6, jlpt:"N5" },
  { char:"生", meaning:"hidup / lahir", onyomi:["せい","しょう"], kunyomi:["い","う","なま"], strokes:5, jlpt:"N5" },
  { char:"子", meaning:"anak", onyomi:["し","す"], kunyomi:["こ"], strokes:3, jlpt:"N5" },
  { char:"女", meaning:"perempuan", onyomi:["じょ","にょ"], kunyomi:["おんな"], strokes:3, jlpt:"N5" },
  { char:"男", meaning:"laki-laki", onyomi:["だん","なん"], kunyomi:["おとこ"], strokes:7, jlpt:"N5" },
  { char:"目", meaning:"mata", onyomi:["もく","ぼく"], kunyomi:["め"], strokes:5, jlpt:"N5" },
  { char:"耳", meaning:"telinga", onyomi:["じ"], kunyomi:["みみ"], strokes:6, jlpt:"N5" },
  { char:"口", meaning:"mulut", onyomi:["こう","く"], kunyomi:["くち"], strokes:3, jlpt:"N5" },
  { char:"手", meaning:"tangan", onyomi:["しゅ"], kunyomi:["て"], strokes:4, jlpt:"N5" },
  { char:"足", meaning:"kaki", onyomi:["そく"], kunyomi:["あし"], strokes:7, jlpt:"N5" },
  { char:"本", meaning:"buku / asal", onyomi:["ほん"], kunyomi:["もと"], strokes:5, jlpt:"N5" },
  { char:"車", meaning:"kendaraan", onyomi:["しゃ"], kunyomi:["くるま"], strokes:7, jlpt:"N5" },
  { char:"電", meaning:"listrik", onyomi:["でん"], kunyomi:[], strokes:13, jlpt:"N5" },
  { char:"気", meaning:"udara / semangat", onyomi:["き","け"], kunyomi:[], strokes:6, jlpt:"N5" },
  { char:"食", meaning:"makan", onyomi:["しょく","じき"], kunyomi:["た","く"], strokes:9, jlpt:"N5" },
  { char:"飲", meaning:"minum", onyomi:["いん"], kunyomi:["の"], strokes:12, jlpt:"N5" },
  { char:"見", meaning:"melihat", onyomi:["けん"], kunyomi:["み"], strokes:7, jlpt:"N5" },
  { char:"聞", meaning:"mendengar", onyomi:["ぶん","もん"], kunyomi:["き","きこ"], strokes:14, jlpt:"N5" },
  { char:"言", meaning:"berbicara / kata", onyomi:["げん","ごん"], kunyomi:["い","こと"], strokes:7, jlpt:"N5" },
  { char:"行", meaning:"pergi", onyomi:["こう","ぎょう"], kunyomi:["い","ゆ","おこな"], strokes:6, jlpt:"N5" },
  { char:"来", meaning:"datang", onyomi:["らい"], kunyomi:["く","き"], strokes:7, jlpt:"N5" },
  { char:"出", meaning:"keluar", onyomi:["しゅつ","すい"], kunyomi:["で","だ"], strokes:5, jlpt:"N5" },
  { char:"入", meaning:"masuk", onyomi:["にゅう"], kunyomi:["い","はい"], strokes:2, jlpt:"N5" },
  { char:"白", meaning:"putih", onyomi:["はく","びゃく"], kunyomi:["しろ","しら"], strokes:5, jlpt:"N5" },
  { char:"黒", meaning:"hitam", onyomi:["こく"], kunyomi:["くろ"], strokes:11, jlpt:"N5" },
  { char:"赤", meaning:"merah", onyomi:["せき","しゃく"], kunyomi:["あか"], strokes:7, jlpt:"N5" },
  { char:"青", meaning:"biru / hijau", onyomi:["せい","しょう"], kunyomi:["あお"], strokes:8, jlpt:"N5" },
  { char:"花", meaning:"bunga", onyomi:["か"], kunyomi:["はな"], strokes:7, jlpt:"N5" },
  { char:"天", meaning:"langit / surga", onyomi:["てん"], kunyomi:["あめ","あま"], strokes:4, jlpt:"N5" },
  { char:"空", meaning:"langit / kosong", onyomi:["くう"], kunyomi:["そら","あ","から"], strokes:8, jlpt:"N5" },
  { char:"雨", meaning:"hujan", onyomi:["う"], kunyomi:["あめ","あま"], strokes:8, jlpt:"N5" },
  { char:"犬", meaning:"anjing", onyomi:["けん"], kunyomi:["いぬ"], strokes:4, jlpt:"N5" },
  { char:"猫", meaning:"kucing", onyomi:["びょう"], kunyomi:["ねこ"], strokes:11, jlpt:"N5" },
  { char:"魚", meaning:"ikan", onyomi:["ぎょ"], kunyomi:["さかな","うお"], strokes:11, jlpt:"N5" },
  { char:"鳥", meaning:"burung", onyomi:["ちょう"], kunyomi:["とり"], strokes:11, jlpt:"N5" },
  { char:"東", meaning:"timur", onyomi:["とう"], kunyomi:["ひがし"], strokes:8, jlpt:"N5" },
  { char:"西", meaning:"barat", onyomi:["せい","さい"], kunyomi:["にし"], strokes:6, jlpt:"N5" },
  { char:"南", meaning:"selatan", onyomi:["なん","な"], kunyomi:["みなみ"], strokes:9, jlpt:"N5" },
  { char:"北", meaning:"utara", onyomi:["ほく"], kunyomi:["きた"], strokes:5, jlpt:"N5" },

  // ══════════════════════════════════════════════════════════════════
  // N4 — 166 kanji
  // ══════════════════════════════════════════════════════════════════
  { char:"会", meaning:"bertemu / rapat", onyomi:["かい","え"], kunyomi:["あ"], strokes:6, jlpt:"N4" },
  { char:"員", meaning:"anggota", onyomi:["いん"], kunyomi:[], strokes:10, jlpt:"N4" },
  { char:"映", meaning:"memantulkan / memancarkan", onyomi:["えい"], kunyomi:["うつ","は"], strokes:9, jlpt:"N4" },
  { char:"音", meaning:"suara", onyomi:["おん","いん"], kunyomi:["おと","ね"], strokes:9, jlpt:"N4" },
  { char:"家", meaning:"rumah / keluarga", onyomi:["か","け"], kunyomi:["いえ","や"], strokes:10, jlpt:"N4" },
  { char:"歌", meaning:"lagu / bernyanyi", onyomi:["か"], kunyomi:["うた"], strokes:14, jlpt:"N4" },
  { char:"画", meaning:"gambar / film", onyomi:["が","かく"], kunyomi:["えが"], strokes:8, jlpt:"N4" },
  { char:"海", meaning:"laut / samudra", onyomi:["かい"], kunyomi:["うみ"], strokes:9, jlpt:"N4" },
  { char:"館", meaning:"gedung / aula", onyomi:["かん"], kunyomi:[], strokes:16, jlpt:"N4" },
  { char:"起", meaning:"bangun / terjadi", onyomi:["き"], kunyomi:["お"], strokes:10, jlpt:"N4" },
  { char:"急", meaning:"terburu-buru / mendadak", onyomi:["きゅう"], kunyomi:["いそ"], strokes:9, jlpt:"N4" },
  { char:"牛", meaning:"sapi", onyomi:["ぎゅう"], kunyomi:["うし"], strokes:4, jlpt:"N4" },
  { char:"強", meaning:"kuat", onyomi:["きょう","ごう"], kunyomi:["つよ","し"], strokes:11, jlpt:"N4" },
  { char:"教", meaning:"mengajar", onyomi:["きょう"], kunyomi:["おし","おそ"], strokes:11, jlpt:"N4" },
  { char:"橋", meaning:"jembatan", onyomi:["きょう"], kunyomi:["はし"], strokes:16, jlpt:"N4" },
  { char:"近", meaning:"dekat", onyomi:["きん"], kunyomi:["ちか"], strokes:7, jlpt:"N4" },
  { char:"区", meaning:"distrik / kawasan", onyomi:["く"], kunyomi:[], strokes:4, jlpt:"N4" },
  { char:"苦", meaning:"pahit / penderitaan", onyomi:["く"], kunyomi:["くる","にが"], strokes:8, jlpt:"N4" },
  { char:"具", meaning:"alat / perabot", onyomi:["ぐ"], kunyomi:[], strokes:8, jlpt:"N4" },
  { char:"建", meaning:"membangun", onyomi:["けん","こん"], kunyomi:["た","たて"], strokes:9, jlpt:"N4" },
  { char:"元", meaning:"asal / dasar", onyomi:["げん","がん"], kunyomi:["もと"], strokes:4, jlpt:"N4" },
  { char:"古", meaning:"kuno / tua", onyomi:["こ"], kunyomi:["ふる"], strokes:5, jlpt:"N4" },
  { char:"午", meaning:"siang / tengah hari", onyomi:["ご"], kunyomi:[], strokes:4, jlpt:"N4" },
  { char:"工", meaning:"pekerjaan / industri", onyomi:["こう","く"], kunyomi:[], strokes:3, jlpt:"N4" },
  { char:"光", meaning:"cahaya / sinar", onyomi:["こう"], kunyomi:["ひかり","ひか"], strokes:6, jlpt:"N4" },
  { char:"考", meaning:"berpikir", onyomi:["こう"], kunyomi:["かんが"], strokes:6, jlpt:"N4" },
  { char:"号", meaning:"nomor / nama", onyomi:["ごう"], kunyomi:[], strokes:5, jlpt:"N4" },
  { char:"合", meaning:"cocok / bersatu", onyomi:["ごう","がっ","かっ"], kunyomi:["あ"], strokes:6, jlpt:"N4" },
  { char:"黒", meaning:"hitam", onyomi:["こく"], kunyomi:["くろ"], strokes:11, jlpt:"N5" },
  { char:"細", meaning:"tipis / halus / detail", onyomi:["さい"], kunyomi:["ほそ","こま"], strokes:11, jlpt:"N4" },
  { char:"作", meaning:"membuat / karya", onyomi:["さく","さ"], kunyomi:["つく"], strokes:7, jlpt:"N4" },
  { char:"止", meaning:"berhenti", onyomi:["し"], kunyomi:["と","や"], strokes:4, jlpt:"N4" },
  { char:"借", meaning:"meminjam", onyomi:["しゃく"], kunyomi:["か"], strokes:10, jlpt:"N4" },
  { char:"弱", meaning:"lemah", onyomi:["じゃく"], kunyomi:["よわ"], strokes:10, jlpt:"N4" },
  { char:"主", meaning:"tuan / utama", onyomi:["しゅ","す"], kunyomi:["ぬし","おも"], strokes:5, jlpt:"N4" },
  { char:"乗", meaning:"naik / menaiki", onyomi:["じょう"], kunyomi:["の"], strokes:9, jlpt:"N4" },
  { char:"場", meaning:"tempat", onyomi:["じょう"], kunyomi:["ば"], strokes:12, jlpt:"N4" },
  { char:"色", meaning:"warna", onyomi:["しょく","しき"], kunyomi:["いろ"], strokes:6, jlpt:"N4" },
  { char:"心", meaning:"hati / pikiran", onyomi:["しん"], kunyomi:["こころ"], strokes:4, jlpt:"N4" },
  { char:"親", meaning:"orang tua / akrab", onyomi:["しん"], kunyomi:["おや","した"], strokes:16, jlpt:"N4" },
  { char:"真", meaning:"sejati / kebenaran", onyomi:["しん"], kunyomi:["ま","まこと"], strokes:10, jlpt:"N4" },
  { char:"数", meaning:"angka / banyak", onyomi:["すう","く"], kunyomi:["かず","かぞ"], strokes:13, jlpt:"N4" },
  { char:"声", meaning:"suara / bunyi", onyomi:["せい","しょう"], kunyomi:["こえ"], strokes:7, jlpt:"N4" },
  { char:"世", meaning:"dunia / generasi", onyomi:["せい","せ"], kunyomi:["よ"], strokes:5, jlpt:"N4" },
  { char:"正", meaning:"benar / lurus", onyomi:["せい","しょう"], kunyomi:["ただ","まさ"], strokes:5, jlpt:"N4" },
  { char:"切", meaning:"memotong / penting", onyomi:["せつ","さい"], kunyomi:["き"], strokes:4, jlpt:"N4" },
  { char:"専", meaning:"spesialis / khusus", onyomi:["せん"], kunyomi:["もっぱ"], strokes:9, jlpt:"N4" },
  { char:"走", meaning:"berlari", onyomi:["そう"], kunyomi:["はし"], strokes:7, jlpt:"N4" },
  { char:"体", meaning:"tubuh", onyomi:["たい","てい"], kunyomi:["からだ"], strokes:7, jlpt:"N4" },
  { char:"台", meaning:"panggung / platform", onyomi:["だい","たい"], kunyomi:[], strokes:5, jlpt:"N4" },
  { char:"地", meaning:"tanah / daerah", onyomi:["ち","じ"], kunyomi:[], strokes:6, jlpt:"N4" },
  { char:"茶", meaning:"teh", onyomi:["ちゃ","さ"], kunyomi:[], strokes:9, jlpt:"N4" },
  { char:"着", meaning:"tiba / memakai", onyomi:["ちゃく"], kunyomi:["き","つ"], strokes:12, jlpt:"N4" },
  { char:"注", meaning:"menuangkan / perhatian", onyomi:["ちゅう"], kunyomi:["そそ"], strokes:8, jlpt:"N4" },
  { char:"朝", meaning:"pagi", onyomi:["ちょう"], kunyomi:["あさ"], strokes:12, jlpt:"N4" },
  { char:"長", meaning:"panjang / pemimpin", onyomi:["ちょう"], kunyomi:["なが","おさ"], strokes:8, jlpt:"N4" },
  { char:"弟", meaning:"adik laki-laki", onyomi:["てい","だい","で"], kunyomi:["おとうと"], strokes:7, jlpt:"N4" },
  { char:"冬", meaning:"musim dingin", onyomi:["とう"], kunyomi:["ふゆ"], strokes:5, jlpt:"N4" },
  { char:"当", meaning:"mengenai / sesuai", onyomi:["とう"], kunyomi:["あ","あた"], strokes:6, jlpt:"N4" },
  { char:"動", meaning:"bergerak", onyomi:["どう"], kunyomi:["うご"], strokes:11, jlpt:"N4" },
  { char:"道", meaning:"jalan", onyomi:["どう","とう"], kunyomi:["みち"], strokes:12, jlpt:"N4" },
  { char:"特", meaning:"khusus / istimewa", onyomi:["とく"], kunyomi:[], strokes:10, jlpt:"N4" },
  { char:"肉", meaning:"daging", onyomi:["にく"], kunyomi:[], strokes:6, jlpt:"N4" },
  { char:"農", meaning:"pertanian", onyomi:["のう"], kunyomi:[], strokes:13, jlpt:"N4" },
  { char:"買", meaning:"membeli", onyomi:["ばい"], kunyomi:["か"], strokes:12, jlpt:"N4" },
  { char:"走", meaning:"berlari", onyomi:["そう"], kunyomi:["はし"], strokes:7, jlpt:"N4" },
  { char:"番", meaning:"nomor urut / giliran", onyomi:["ばん"], kunyomi:[], strokes:12, jlpt:"N4" },
  { char:"病", meaning:"sakit / penyakit", onyomi:["びょう"], kunyomi:["やまい"], strokes:10, jlpt:"N4" },
  { char:"父", meaning:"ayah", onyomi:["ふ"], kunyomi:["ちち"], strokes:4, jlpt:"N4" },
  { char:"不", meaning:"tidak / bukan", onyomi:["ふ","ぶ"], kunyomi:[], strokes:4, jlpt:"N4" },
  { char:"風", meaning:"angin", onyomi:["ふう","ふ"], kunyomi:["かぜ","かざ"], strokes:9, jlpt:"N4" },
  { char:"服", meaning:"pakaian", onyomi:["ふく"], kunyomi:[], strokes:8, jlpt:"N4" },
  { char:"部", meaning:"bagian / departemen", onyomi:["ぶ"], kunyomi:[], strokes:11, jlpt:"N4" },
  { char:"品", meaning:"barang / kualitas", onyomi:["ひん","ぽん"], kunyomi:["しな"], strokes:9, jlpt:"N4" },
  { char:"平", meaning:"datar / damai", onyomi:["へい","びょう"], kunyomi:["たい","ひら"], strokes:5, jlpt:"N4" },
  { char:"文", meaning:"tulisan / kalimat", onyomi:["ぶん","もん"], kunyomi:["ふみ"], strokes:4, jlpt:"N4" },
  { char:"方", meaning:"arah / cara", onyomi:["ほう"], kunyomi:["かた"], strokes:4, jlpt:"N4" },
  { char:"忘", meaning:"lupa", onyomi:["ぼう"], kunyomi:["わす"], strokes:7, jlpt:"N4" },
  { char:"毎", meaning:"setiap", onyomi:["まい"], kunyomi:[], strokes:6, jlpt:"N4" },
  { char:"妹", meaning:"adik perempuan", onyomi:["まい"], kunyomi:["いもうと"], strokes:8, jlpt:"N4" },
  { char:"末", meaning:"ujung / akhir", onyomi:["まつ","ばつ"], kunyomi:["すえ"], strokes:5, jlpt:"N4" },
  { char:"問", meaning:"pertanyaan / masalah", onyomi:["もん"], kunyomi:["と","とい"], strokes:11, jlpt:"N4" },
  { char:"役", meaning:"peran / manfaat", onyomi:["やく","えき"], kunyomi:[], strokes:7, jlpt:"N4" },
  { char:"薬", meaning:"obat", onyomi:["やく"], kunyomi:["くすり"], strokes:16, jlpt:"N4" },
  { char:"旅", meaning:"perjalanan", onyomi:["りょ"], kunyomi:["たび"], strokes:10, jlpt:"N4" },
  { char:"理", meaning:"alasan / mengurus", onyomi:["り"], kunyomi:[], strokes:11, jlpt:"N4" },
  { char:"料", meaning:"bahan / biaya", onyomi:["りょう"], kunyomi:[], strokes:10, jlpt:"N4" },
  { char:"力", meaning:"kekuatan", onyomi:["りょく","りき"], kunyomi:["ちから"], strokes:2, jlpt:"N4" },
  { char:"立", meaning:"berdiri", onyomi:["りつ","りゅう"], kunyomi:["た"], strokes:5, jlpt:"N4" },
  { char:"楽", meaning:"menyenangkan / mudah", onyomi:["がく","らく"], kunyomi:["たの"], strokes:13, jlpt:"N4" },
  { char:"自", meaning:"diri sendiri", onyomi:["じ","し"], kunyomi:["みずか"], strokes:6, jlpt:"N4" },
  { char:"仕", meaning:"melayani / mengabdi", onyomi:["し"], kunyomi:["つか"], strokes:5, jlpt:"N4" },
  { char:"事", meaning:"hal / peristiwa", onyomi:["じ","ず"], kunyomi:["こと"], strokes:8, jlpt:"N4" },
  { char:"週", meaning:"minggu", onyomi:["しゅう"], kunyomi:[], strokes:11, jlpt:"N4" },
  { char:"今", meaning:"sekarang", onyomi:["こん","きん"], kunyomi:["いま"], strokes:4, jlpt:"N4" },
  { char:"何", meaning:"apa / berapa", onyomi:["か"], kunyomi:["なに","なん"], strokes:7, jlpt:"N4" },
  { char:"書", meaning:"menulis / buku", onyomi:["しょ"], kunyomi:["か"], strokes:10, jlpt:"N4" },
  { char:"読", meaning:"membaca", onyomi:["どく","とく"], kunyomi:["よ"], strokes:14, jlpt:"N4" },
  { char:"話", meaning:"berbicara / cerita", onyomi:["わ"], kunyomi:["はな","はなし"], strokes:13, jlpt:"N4" },
  { char:"思", meaning:"berpikir / merasa", onyomi:["し"], kunyomi:["おも"], strokes:9, jlpt:"N4" },
  { char:"知", meaning:"mengetahui", onyomi:["ち"], kunyomi:["し"], strokes:8, jlpt:"N4" },
  { char:"友", meaning:"teman", onyomi:["ゆう"], kunyomi:["とも"], strokes:4, jlpt:"N4" },
  { char:"門", meaning:"gerbang", onyomi:["もん"], kunyomi:["かど"], strokes:8, jlpt:"N4" },
  { char:"兄", meaning:"kakak laki-laki", onyomi:["けい","きょう"], kunyomi:["あに"], strokes:5, jlpt:"N4" },
  { char:"姉", meaning:"kakak perempuan", onyomi:["し"], kunyomi:["あね"], strokes:8, jlpt:"N4" },
  { char:"母", meaning:"ibu", onyomi:["ぼ"], kunyomi:["はは"], strokes:5, jlpt:"N4" },
  { char:"売", meaning:"menjual", onyomi:["ばい"], kunyomi:["う"], strokes:7, jlpt:"N4" },
  { char:"新", meaning:"baru", onyomi:["しん"], kunyomi:["あたら","あら","にい"], strokes:13, jlpt:"N4" },
  { char:"好", meaning:"suka / baik", onyomi:["こう"], kunyomi:["す","この"], strokes:6, jlpt:"N4" },
  { char:"多", meaning:"banyak", onyomi:["た"], kunyomi:["おお"], strokes:6, jlpt:"N4" },
  { char:"少", meaning:"sedikit", onyomi:["しょう"], kunyomi:["すこ","すく"], strokes:4, jlpt:"N4" },
  { char:"高", meaning:"tinggi / mahal", onyomi:["こう"], kunyomi:["たか"], strokes:10, jlpt:"N4" },
  { char:"安", meaning:"murah / aman", onyomi:["あん"], kunyomi:["やす"], strokes:6, jlpt:"N4" },
  { char:"早", meaning:"cepat / pagi", onyomi:["そう","さっ"], kunyomi:["はや"], strokes:6, jlpt:"N4" },
  { char:"待", meaning:"menunggu", onyomi:["たい"], kunyomi:["ま"], strokes:9, jlpt:"N4" },
  { char:"寝", meaning:"tidur", onyomi:["しん"], kunyomi:["ね"], strokes:13, jlpt:"N4" },
  { char:"開", meaning:"membuka", onyomi:["かい"], kunyomi:["あ","ひら"], strokes:12, jlpt:"N4" },
  { char:"閉", meaning:"menutup", onyomi:["へい"], kunyomi:["し","と"], strokes:11, jlpt:"N4" },
  { char:"使", meaning:"menggunakan", onyomi:["し"], kunyomi:["つか"], strokes:8, jlpt:"N4" },
  { char:"習", meaning:"belajar / berlatih", onyomi:["しゅう"], kunyomi:["なら"], strokes:11, jlpt:"N4" },
  { char:"春", meaning:"musim semi", onyomi:["しゅん"], kunyomi:["はる"], strokes:9, jlpt:"N4" },
  { char:"夏", meaning:"musim panas", onyomi:["か","げ"], kunyomi:["なつ"], strokes:10, jlpt:"N4" },
  { char:"秋", meaning:"musim gugur", onyomi:["しゅう"], kunyomi:["あき"], strokes:9, jlpt:"N4" },
  { char:"夜", meaning:"malam", onyomi:["や"], kunyomi:["よる","よ"], strokes:8, jlpt:"N4" },
  { char:"昼", meaning:"siang hari", onyomi:["ちゅう"], kunyomi:["ひる"], strokes:9, jlpt:"N4" },
  { char:"週", meaning:"minggu", onyomi:["しゅう"], kunyomi:[], strokes:11, jlpt:"N4" },
  { char:"去", meaning:"pergi / lalu", onyomi:["きょ","こ"], kunyomi:["さ"], strokes:5, jlpt:"N4" },
  { char:"帰", meaning:"kembali / pulang", onyomi:["き"], kunyomi:["かえ"], strokes:10, jlpt:"N4" },
  { char:"持", meaning:"memegang / memiliki", onyomi:["じ"], kunyomi:["も"], strokes:9, jlpt:"N4" },
  { char:"間", meaning:"antara / interval", onyomi:["かん","けん"], kunyomi:["あいだ","ま"], strokes:12, jlpt:"N4" },
  { char:"運", meaning:"nasib / membawa", onyomi:["うん"], kunyomi:["はこ"], strokes:12, jlpt:"N4" },
  { char:"步", meaning:"berjalan kaki", onyomi:["ほ","ぶ"], kunyomi:["ある","あゆ"], strokes:8, jlpt:"N4" },
  { char:"切", meaning:"memotong", onyomi:["せつ","さい"], kunyomi:["き"], strokes:4, jlpt:"N4" },
  { char:"決", meaning:"memutuskan", onyomi:["けつ"], kunyomi:["き"], strokes:7, jlpt:"N4" },
  { char:"始", meaning:"mulai", onyomi:["し"], kunyomi:["はじ"], strokes:8, jlpt:"N4" },
  { char:"終", meaning:"berakhir", onyomi:["しゅう"], kunyomi:["お","おわ"], strokes:11, jlpt:"N4" },
  { char:"続", meaning:"berlanjut", onyomi:["ぞく"], kunyomi:["つづ"], strokes:13, jlpt:"N4" },
  { char:"変", meaning:"berubah / aneh", onyomi:["へん"], kunyomi:["か"], strokes:9, jlpt:"N4" },
  { char:"集", meaning:"mengumpulkan", onyomi:["しゅう"], kunyomi:["あつ"], strokes:12, jlpt:"N4" },
  { char:"選", meaning:"memilih", onyomi:["せん"], kunyomi:["えら"], strokes:15, jlpt:"N4" },
  { char:"転", meaning:"berputar / pindah", onyomi:["てん"], kunyomi:["ころ","うた"], strokes:11, jlpt:"N4" },
  { char:"返", meaning:"kembali / mengembalikan", onyomi:["へん"], kunyomi:["かえ"], strokes:7, jlpt:"N4" },
  { char:"送", meaning:"mengirim", onyomi:["そう"], kunyomi:["おく"], strokes:9, jlpt:"N4" },
  { char:"通", meaning:"lewat / hubungan", onyomi:["つう","つ"], kunyomi:["とお","かよ"], strokes:10, jlpt:"N4" },
  { char:"太", meaning:"gemuk / tebal", onyomi:["た","たい"], kunyomi:["ふと"], strokes:4, jlpt:"N4" },
  { char:"細", meaning:"tipis / detail", onyomi:["さい"], kunyomi:["ほそ","こま"], strokes:11, jlpt:"N4" },
  { char:"丸", meaning:"bulat", onyomi:["がん"], kunyomi:["まる"], strokes:3, jlpt:"N4" },
  { char:"重", meaning:"berat / penting", onyomi:["じゅう","ちょう"], kunyomi:["おも","かさ"], strokes:9, jlpt:"N4" },
  { char:"軽", meaning:"ringan", onyomi:["けい"], kunyomi:["かる","かろ"], strokes:12, jlpt:"N4" },
  { char:"広", meaning:"luas / lebar", onyomi:["こう"], kunyomi:["ひろ"], strokes:5, jlpt:"N4" },
  { char:"暗", meaning:"gelap", onyomi:["あん"], kunyomi:["くら"], strokes:13, jlpt:"N4" },
  { char:"明", meaning:"cerah / jelas", onyomi:["めい","みょう"], kunyomi:["あか","あき","あきら"], strokes:8, jlpt:"N4" },

  // ══════════════════════════════════════════════════════════════════
  // N3 — 367 kanji (representative 200+)
  // ══════════════════════════════════════════════════════════════════
  { char:"民", meaning:"rakyat", onyomi:["みん"], kunyomi:["たみ"], strokes:5, jlpt:"N3" },
  { char:"以", meaning:"berdasarkan / sejak", onyomi:["い"], kunyomi:[], strokes:5, jlpt:"N3" },
  { char:"化", meaning:"transformasi", onyomi:["か","け"], kunyomi:["ば"], strokes:4, jlpt:"N3" },
  { char:"意", meaning:"maksud / pikiran", onyomi:["い"], kunyomi:[], strokes:13, jlpt:"N3" },
  { char:"同", meaning:"sama", onyomi:["どう"], kunyomi:["おな"], strokes:6, jlpt:"N3" },
  { char:"実", meaning:"kenyataan / buah", onyomi:["じつ"], kunyomi:["み","みの","まこと"], strokes:8, jlpt:"N3" },
  { char:"発", meaning:"berangkat / muncul", onyomi:["はつ","ほつ"], kunyomi:["た"], strokes:9, jlpt:"N3" },
  { char:"題", meaning:"tema / judul", onyomi:["だい"], kunyomi:[], strokes:18, jlpt:"N3" },
  { char:"直", meaning:"lurus / memperbaiki", onyomi:["ちょく","じき"], kunyomi:["なお","ただ"], strokes:8, jlpt:"N3" },
  { char:"信", meaning:"percaya", onyomi:["しん"], kunyomi:["まこと"], strokes:9, jlpt:"N3" },
  { char:"受", meaning:"menerima", onyomi:["じゅ"], kunyomi:["う"], strokes:8, jlpt:"N3" },
  { char:"表", meaning:"permukaan / menyatakan", onyomi:["ひょう"], kunyomi:["おもて","あらわ"], strokes:8, jlpt:"N3" },
  { char:"働", meaning:"bekerja", onyomi:["どう"], kunyomi:["はたら"], strokes:13, jlpt:"N3" },
  { char:"勉", meaning:"bekerja keras / belajar", onyomi:["べん"], kunyomi:[], strokes:10, jlpt:"N3" },
  { char:"活", meaning:"hidup / aktif", onyomi:["かつ"], kunyomi:["い"], strokes:9, jlpt:"N3" },
  { char:"進", meaning:"maju", onyomi:["しん"], kunyomi:["すす"], strokes:11, jlpt:"N3" },
  { char:"場", meaning:"tempat / lapangan", onyomi:["じょう"], kunyomi:["ば"], strokes:12, jlpt:"N3" },
  { char:"現", meaning:"sekarang / muncul", onyomi:["げん"], kunyomi:["あらわ"], strokes:11, jlpt:"N3" },
  { char:"政", meaning:"pemerintahan / politik", onyomi:["せい","しょう"], kunyomi:["まつりごと"], strokes:9, jlpt:"N3" },
  { char:"府", meaning:"prefektur / kantor", onyomi:["ふ"], kunyomi:[], strokes:8, jlpt:"N3" },
  { char:"県", meaning:"prefektur", onyomi:["けん"], kunyomi:[], strokes:9, jlpt:"N3" },
  { char:"議", meaning:"rapat / diskusi", onyomi:["ぎ"], kunyomi:[], strokes:20, jlpt:"N3" },
  { char:"会", meaning:"bertemu / rapat", onyomi:["かい","え"], kunyomi:["あ"], strokes:6, jlpt:"N3" },
  { char:"報", meaning:"laporan / membalas", onyomi:["ほう"], kunyomi:["むく"], strokes:12, jlpt:"N3" },
  { char:"研", meaning:"meneliti / mengasah", onyomi:["けん"], kunyomi:[], strokes:9, jlpt:"N3" },
  { char:"究", meaning:"meneliti / mengkaji", onyomi:["きゅう"], kunyomi:["きわ"], strokes:7, jlpt:"N3" },
  { char:"産", meaning:"melahirkan / produksi", onyomi:["さん"], kunyomi:["う","うま"], strokes:11, jlpt:"N3" },
  { char:"業", meaning:"pekerjaan / industri", onyomi:["ぎょう","ごう"], kunyomi:["わざ"], strokes:13, jlpt:"N3" },
  { char:"技", meaning:"keahlian / teknik", onyomi:["ぎ"], kunyomi:["わざ"], strokes:7, jlpt:"N3" },
  { char:"術", meaning:"seni / teknik", onyomi:["じゅつ"], kunyomi:[], strokes:11, jlpt:"N3" },
  { char:"情", meaning:"perasaan / kondisi", onyomi:["じょう","せい"], kunyomi:["なさ"], strokes:11, jlpt:"N3" },
  { char:"感", meaning:"merasakan", onyomi:["かん"], kunyomi:[], strokes:13, jlpt:"N3" },
  { char:"想", meaning:"memikirkan / membayangkan", onyomi:["そう","そ"], kunyomi:[], strokes:13, jlpt:"N3" },
  { char:"念", meaning:"pikiran / perasaan kuat", onyomi:["ねん"], kunyomi:[], strokes:8, jlpt:"N3" },
  { char:"観", meaning:"pandangan / mengamati", onyomi:["かん"], kunyomi:["み"], strokes:18, jlpt:"N3" },
  { char:"点", meaning:"titik / nilai", onyomi:["てん"], kunyomi:[], strokes:9, jlpt:"N3" },
  { char:"回", meaning:"kembali / kali", onyomi:["かい","え"], kunyomi:["まわ"], strokes:6, jlpt:"N3" },
  { char:"向", meaning:"menghadap / menuju", onyomi:["こう"], kunyomi:["む","むか","むこう"], strokes:6, jlpt:"N3" },
  { char:"対", meaning:"menghadapi / pasangan", onyomi:["たい","つい"], kunyomi:[], strokes:7, jlpt:"N3" },
  { char:"関", meaning:"berkaitan / berhubungan", onyomi:["かん"], kunyomi:["せき","かか"], strokes:14, jlpt:"N3" },
  { char:"係", meaning:"hubungan / petugas", onyomi:["けい"], kunyomi:["かか"], strokes:9, jlpt:"N3" },
  { char:"連", meaning:"bersambung / membawa", onyomi:["れん"], kunyomi:["つら","つれ"], strokes:10, jlpt:"N3" },
  { char:"結", meaning:"mengikat / kesiimpulan", onyomi:["けつ"], kunyomi:["むす","ゆ"], strokes:12, jlpt:"N3" },
  { char:"果", meaning:"hasil / buah", onyomi:["か"], kunyomi:["は","はて"], strokes:8, jlpt:"N3" },
  { char:"効", meaning:"efektif / hasil", onyomi:["こう"], kunyomi:["き"], strokes:8, jlpt:"N3" },
  { char:"制", meaning:"sistem / mengontrol", onyomi:["せい"], kunyomi:[], strokes:8, jlpt:"N3" },
  { char:"度", meaning:"derajat / kali", onyomi:["ど","たく"], kunyomi:["たび"], strokes:9, jlpt:"N3" },
  { char:"量", meaning:"kuantitas / jumlah", onyomi:["りょう"], kunyomi:["はか"], strokes:12, jlpt:"N3" },
  { char:"質", meaning:"kualitas / zat", onyomi:["しつ","しち"], kunyomi:[], strokes:15, jlpt:"N3" },
  { char:"価", meaning:"harga / nilai", onyomi:["か"], kunyomi:["あたい"], strokes:8, jlpt:"N3" },
  { char:"格", meaning:"status / format", onyomi:["かく","こう"], kunyomi:[], strokes:10, jlpt:"N3" },
  { char:"規", meaning:"aturan / standar", onyomi:["き"], kunyomi:[], strokes:11, jlpt:"N3" },
  { char:"則", meaning:"aturan", onyomi:["そく"], kunyomi:["のり"], strokes:9, jlpt:"N3" },
  { char:"法", meaning:"hukum / metode", onyomi:["ほう","はっ","ほっ"], kunyomi:[], strokes:8, jlpt:"N3" },
  { char:"律", meaning:"aturan / ritme", onyomi:["りつ","りち"], kunyomi:[], strokes:9, jlpt:"N3" },
  { char:"型", meaning:"bentuk / model", onyomi:["けい"], kunyomi:["かた"], strokes:9, jlpt:"N3" },
  { char:"様", meaning:"cara / kondisi / tuan", onyomi:["よう"], kunyomi:["さま"], strokes:14, jlpt:"N3" },
  { char:"式", meaning:"upacara / rumus", onyomi:["しき"], kunyomi:[], strokes:6, jlpt:"N3" },
  { char:"状", meaning:"kondisi / surat", onyomi:["じょう"], kunyomi:[], strokes:7, jlpt:"N3" },
  { char:"態", meaning:"sikap / kondisi", onyomi:["たい"], kunyomi:[], strokes:14, jlpt:"N3" },
  { char:"形", meaning:"bentuk", onyomi:["けい","ぎょう"], kunyomi:["かた","かたち"], strokes:7, jlpt:"N3" },
  { char:"位", meaning:"posisi / peringkat", onyomi:["い"], kunyomi:["くらい"], strokes:7, jlpt:"N3" },
  { char:"列", meaning:"barisan / baris", onyomi:["れつ"], kunyomi:[], strokes:6, jlpt:"N3" },
  { char:"順", meaning:"urutan / mengikuti", onyomi:["じゅん"], kunyomi:["したが"], strokes:12, jlpt:"N3" },
  { char:"番", meaning:"giliran / nomor", onyomi:["ばん"], kunyomi:[], strokes:12, jlpt:"N3" },
  { char:"号", meaning:"nomor / nama", onyomi:["ごう"], kunyomi:[], strokes:5, jlpt:"N3" },
  { char:"次", meaning:"berikutnya", onyomi:["じ","し"], kunyomi:["つぎ","つ"], strokes:6, jlpt:"N3" },
  { char:"初", meaning:"pertama / awal", onyomi:["しょ"], kunyomi:["はじ","はつ","うい","そ"], strokes:7, jlpt:"N3" },
  { char:"末", meaning:"akhir / ujung", onyomi:["まつ","ばつ"], kunyomi:["すえ"], strokes:5, jlpt:"N3" },
  { char:"期", meaning:"periode / jangka waktu", onyomi:["き","ご"], kunyomi:[], strokes:12, jlpt:"N3" },
  { char:"間", meaning:"antara / waktu", onyomi:["かん","けん"], kunyomi:["あいだ","ま"], strokes:12, jlpt:"N3" },
  { char:"際", meaning:"saat / perbatasan", onyomi:["さい"], kunyomi:["きわ"], strokes:14, jlpt:"N3" },
  { char:"後", meaning:"setelah / belakang", onyomi:["ご","こう"], kunyomi:["あと","うし","のち"], strokes:9, jlpt:"N3" },
  { char:"前", meaning:"sebelum / depan", onyomi:["ぜん"], kunyomi:["まえ"], strokes:9, jlpt:"N3" },
  { char:"外", meaning:"luar", onyomi:["がい","げ"], kunyomi:["そと","はず","ほか"], strokes:5, jlpt:"N3" },
  { char:"内", meaning:"dalam / interior", onyomi:["ない","だい"], kunyomi:["うち"], strokes:4, jlpt:"N3" },
  { char:"各", meaning:"masing-masing", onyomi:["かく"], kunyomi:["おのおの"], strokes:6, jlpt:"N3" },
  { char:"全", meaning:"semua / lengkap", onyomi:["ぜん"], kunyomi:["まった","すべ"], strokes:6, jlpt:"N3" },
  { char:"無", meaning:"tidak ada / nol", onyomi:["む","ぶ"], kunyomi:["な"], strokes:12, jlpt:"N3" },
  { char:"有", meaning:"ada / memiliki", onyomi:["ゆう","う"], kunyomi:["あ"], strokes:6, jlpt:"N3" },
  { char:"必", meaning:"pasti / perlu", onyomi:["ひつ"], kunyomi:["かなら"], strokes:5, jlpt:"N3" },
  { char:"要", meaning:"perlu / penting", onyomi:["よう"], kunyomi:["い","かなめ"], strokes:9, jlpt:"N3" },
  { char:"的", meaning:"sasaran / -nya", onyomi:["てき"], kunyomi:["まと"], strokes:8, jlpt:"N3" },
  { char:"機", meaning:"mesin / kesempatan", onyomi:["き"], kunyomi:["はた"], strokes:16, jlpt:"N3" },
  { char:"能", meaning:"kemampuan / bisa", onyomi:["のう"], kunyomi:[], strokes:10, jlpt:"N3" },
  { char:"力", meaning:"kekuatan", onyomi:["りょく","りき"], kunyomi:["ちから"], strokes:2, jlpt:"N3" },
  { char:"求", meaning:"meminta / mencari", onyomi:["きゅう"], kunyomi:["もと"], strokes:7, jlpt:"N3" },
  { char:"得", meaning:"mendapatkan / bisa", onyomi:["とく"], kunyomi:["え","う"], strokes:11, jlpt:"N3" },
  { char:"失", meaning:"kehilangan / gagal", onyomi:["しつ"], kunyomi:["うしな"], strokes:5, jlpt:"N3" },
  { char:"設", meaning:"mendirikan", onyomi:["せつ"], kunyomi:["もう"], strokes:11, jlpt:"N3" },
  { char:"立", meaning:"berdiri", onyomi:["りつ","りゅう"], kunyomi:["た"], strokes:5, jlpt:"N3" },
  { char:"用", meaning:"menggunakan / keperluan", onyomi:["よう"], kunyomi:["もち"], strokes:5, jlpt:"N3" },
  { char:"増", meaning:"bertambah / meningkat", onyomi:["ぞう"], kunyomi:["ふ","ま"], strokes:14, jlpt:"N3" },
  { char:"減", meaning:"berkurang / menurun", onyomi:["げん"], kunyomi:["へ"], strokes:12, jlpt:"N3" },
  { char:"高", meaning:"tinggi / mahal", onyomi:["こう"], kunyomi:["たか"], strokes:10, jlpt:"N3" },
  { char:"低", meaning:"rendah", onyomi:["てい"], kunyomi:["ひく"], strokes:7, jlpt:"N3" },
  { char:"長", meaning:"panjang / pemimpin", onyomi:["ちょう"], kunyomi:["なが","おさ"], strokes:8, jlpt:"N3" },
  { char:"短", meaning:"pendek", onyomi:["たん"], kunyomi:["みじか"], strokes:12, jlpt:"N3" },
  { char:"深", meaning:"dalam / mendalam", onyomi:["しん"], kunyomi:["ふか"], strokes:11, jlpt:"N3" },
  { char:"浅", meaning:"dangkal", onyomi:["せん"], kunyomi:["あさ"], strokes:9, jlpt:"N3" },
  { char:"速", meaning:"cepat", onyomi:["そく"], kunyomi:["はや"], strokes:10, jlpt:"N3" },
  { char:"遅", meaning:"lambat / terlambat", onyomi:["ち"], kunyomi:["おそ","おく"], strokes:12, jlpt:"N3" },
  { char:"若", meaning:"muda", onyomi:["じゃく","にゃく"], kunyomi:["わか","も"], strokes:8, jlpt:"N3" },
  { char:"老", meaning:"tua", onyomi:["ろう"], kunyomi:["お","ふ"], strokes:6, jlpt:"N3" },
  { char:"近", meaning:"dekat", onyomi:["きん"], kunyomi:["ちか"], strokes:7, jlpt:"N3" },
  { char:"遠", meaning:"jauh", onyomi:["えん","おん"], kunyomi:["とお"], strokes:13, jlpt:"N3" },
  { char:"広", meaning:"luas / lebar", onyomi:["こう"], kunyomi:["ひろ"], strokes:5, jlpt:"N3" },
  { char:"狭", meaning:"sempit", onyomi:["きょう"], kunyomi:["せま","せば"], strokes:9, jlpt:"N3" },
  { char:"暖", meaning:"hangat", onyomi:["だん"], kunyomi:["あたた"], strokes:13, jlpt:"N3" },
  { char:"冷", meaning:"dingin", onyomi:["れい"], kunyomi:["つめ","ひ","さ"], strokes:7, jlpt:"N3" },
  { char:"温", meaning:"suhu / hangat", onyomi:["おん"], kunyomi:["あたた","ぬく"], strokes:12, jlpt:"N3" },
  { char:"熱", meaning:"panas / demam", onyomi:["ねつ"], kunyomi:["あつ"], strokes:15, jlpt:"N3" },
  { char:"軽", meaning:"ringan", onyomi:["けい"], kunyomi:["かる","かろ"], strokes:12, jlpt:"N3" },
  { char:"重", meaning:"berat / penting", onyomi:["じゅう","ちょう"], kunyomi:["おも","かさ"], strokes:9, jlpt:"N3" },
  { char:"固", meaning:"keras / tetap", onyomi:["こ"], kunyomi:["かた"], strokes:8, jlpt:"N3" },
  { char:"柔", meaning:"lembut / fleksibel", onyomi:["じゅう","にゅう"], kunyomi:["やわ"], strokes:9, jlpt:"N3" },
  { char:"鋭", meaning:"tajam / cerdas", onyomi:["えい"], kunyomi:["するど"], strokes:15, jlpt:"N3" },
  { char:"鈍", meaning:"tumpul / lambat", onyomi:["どん"], kunyomi:["にぶ","のろ"], strokes:12, jlpt:"N3" },
  { char:"清", meaning:"bersih / jernih", onyomi:["せい","しょう"], kunyomi:["きよ"], strokes:11, jlpt:"N3" },
  { char:"汚", meaning:"kotor", onyomi:["お"], kunyomi:["よご","きたな"], strokes:6, jlpt:"N3" },
  { char:"明", meaning:"cerah / jelas", onyomi:["めい","みょう"], kunyomi:["あか","あき","あきら"], strokes:8, jlpt:"N3" },
  { char:"暗", meaning:"gelap", onyomi:["あん"], kunyomi:["くら"], strokes:13, jlpt:"N3" },
  { char:"美", meaning:"indah / cantik", onyomi:["び","み"], kunyomi:["うつく"], strokes:9, jlpt:"N3" },
  { char:"醜", meaning:"buruk / jelek", onyomi:["しゅう"], kunyomi:["みにく"], strokes:17, jlpt:"N3" },
  { char:"正", meaning:"benar / lurus", onyomi:["せい","しょう"], kunyomi:["ただ","まさ"], strokes:5, jlpt:"N3" },
  { char:"誤", meaning:"salah / kesalahan", onyomi:["ご"], kunyomi:["あやま"], strokes:14, jlpt:"N3" },
  { char:"良", meaning:"baik", onyomi:["りょう"], kunyomi:["よ","い"], strokes:7, jlpt:"N3" },
  { char:"悪", meaning:"jahat / buruk", onyomi:["あく","お"], kunyomi:["わる"], strokes:11, jlpt:"N3" },
  { char:"難", meaning:"sulit / kesulitan", onyomi:["なん","な"], kunyomi:["むずか","かた"], strokes:18, jlpt:"N3" },
  { char:"易", meaning:"mudah", onyomi:["い","えき"], kunyomi:["やさ"], strokes:8, jlpt:"N3" },
  { char:"便", meaning:"nyaman / surat", onyomi:["べん","びん"], kunyomi:["たよ"], strokes:9, jlpt:"N3" },
  { char:"不", meaning:"tidak / bukan", onyomi:["ふ","ぶ"], kunyomi:[], strokes:4, jlpt:"N3" },
  { char:"可", meaning:"bisa / diizinkan", onyomi:["か"], kunyomi:[], strokes:5, jlpt:"N3" },
  { char:"否", meaning:"tidak / menolak", onyomi:["ひ"], kunyomi:["いな"], strokes:7, jlpt:"N3" },
  { char:"共", meaning:"bersama", onyomi:["きょう"], kunyomi:["とも"], strokes:6, jlpt:"N3" },
  { char:"別", meaning:"berbeda / berpisah", onyomi:["べつ"], kunyomi:["わか"], strokes:7, jlpt:"N3" },
  { char:"特", meaning:"khusus / istimewa", onyomi:["とく"], kunyomi:[], strokes:10, jlpt:"N3" },
  { char:"普", meaning:"biasa / umum", onyomi:["ふ"], kunyomi:[], strokes:12, jlpt:"N3" },
  { char:"通", meaning:"lewat / umum", onyomi:["つう","つ"], kunyomi:["とお","かよ"], strokes:10, jlpt:"N3" },
  { char:"異", meaning:"berbeda / asing", onyomi:["い"], kunyomi:["こと"], strokes:11, jlpt:"N3" },
  { char:"似", meaning:"mirip / menyerupai", onyomi:["じ"], kunyomi:["に"], strokes:7, jlpt:"N3" },
  { char:"当", meaning:"mengenai / tepat", onyomi:["とう"], kunyomi:["あ","あた"], strokes:6, jlpt:"N3" },
  { char:"然", meaning:"alami / begitu", onyomi:["ぜん","ねん"], kunyomi:["しか","しかり","さ"], strokes:12, jlpt:"N3" },
  { char:"如", meaning:"seperti / mirip", onyomi:["じょ","にょ"], kunyomi:["ごと","しか"], strokes:6, jlpt:"N3" },

  // ══════════════════════════════════════════════════════════════════
  // N2 — representative kanji
  // ══════════════════════════════════════════════════════════════════
  { char:"憲", meaning:"konstitusi / hukum dasar", onyomi:["けん"], kunyomi:[], strokes:16, jlpt:"N2" },
  { char:"権", meaning:"hak / wewenang", onyomi:["けん","ごん"], kunyomi:[], strokes:15, jlpt:"N2" },
  { char:"義", meaning:"kebenaran / makna", onyomi:["ぎ"], kunyomi:[], strokes:13, jlpt:"N2" },
  { char:"務", meaning:"tugas / kewajiban", onyomi:["む"], kunyomi:["つと"], strokes:11, jlpt:"N2" },
  { char:"責", meaning:"tanggung jawab", onyomi:["せき"], kunyomi:["せ"], strokes:11, jlpt:"N2" },
  { char:"任", meaning:"tanggung jawab / menyerahkan", onyomi:["にん"], kunyomi:["まか"], strokes:6, jlpt:"N2" },
  { char:"担", meaning:"menanggung / bertanggung jawab", onyomi:["たん"], kunyomi:["かつ","にな"], strokes:8, jlpt:"N2" },
  { char:"負", meaning:"kalah / menanggung", onyomi:["ふ"], kunyomi:["ま","お","おぶ"], strokes:9, jlpt:"N2" },
  { char:"勝", meaning:"menang", onyomi:["しょう"], kunyomi:["か"], strokes:12, jlpt:"N2" },
  { char:"敗", meaning:"kalah / gagal", onyomi:["はい"], kunyomi:["やぶ"], strokes:11, jlpt:"N2" },
  { char:"競", meaning:"bersaing", onyomi:["きょう","けい"], kunyomi:["きそ","せ"], strokes:20, jlpt:"N2" },
  { char:"争", meaning:"bertarung / bersaing", onyomi:["そう"], kunyomi:["あらそ"], strokes:6, jlpt:"N2" },
  { char:"戦", meaning:"perang / pertempuran", onyomi:["せん"], kunyomi:["いくさ","たたか"], strokes:13, jlpt:"N2" },
  { char:"平", meaning:"damai / datar", onyomi:["へい","びょう"], kunyomi:["たい","ひら"], strokes:5, jlpt:"N2" },
  { char:"和", meaning:"harmoni / damai", onyomi:["わ","お"], kunyomi:["やわ","なご"], strokes:8, jlpt:"N2" },
  { char:"統", meaning:"mengelola / mengontrol", onyomi:["とう"], kunyomi:["す"], strokes:12, jlpt:"N2" },
  { char:"治", meaning:"memerintah / menyembuhkan", onyomi:["じ","ち"], kunyomi:["おさ","なお"], strokes:8, jlpt:"N2" },
  { char:"革", meaning:"revolusi / kulit", onyomi:["かく"], kunyomi:["かわ"], strokes:9, jlpt:"N2" },
  { char:"改", meaning:"memperbaiki / mengubah", onyomi:["かい"], kunyomi:["あらた"], strokes:7, jlpt:"N2" },
  { char:"修", meaning:"memperbaiki / berlatih", onyomi:["しゅう","しゅ"], kunyomi:["おさ"], strokes:10, jlpt:"N2" },
  { char:"復", meaning:"pulih / kembali", onyomi:["ふく"], kunyomi:["また"], strokes:12, jlpt:"N2" },
  { char:"興", meaning:"berkembang / kesenangan", onyomi:["こう","きょう"], kunyomi:["おこ","おき"], strokes:16, jlpt:"N2" },
  { char:"廃", meaning:"menghapuskan / runtuh", onyomi:["はい"], kunyomi:["すた"], strokes:12, jlpt:"N2" },
  { char:"破", meaning:"menghancurkan / merusak", onyomi:["は"], kunyomi:["やぶ"], strokes:10, jlpt:"N2" },
  { char:"壊", meaning:"rusak / menghancurkan", onyomi:["かい"], kunyomi:["こわ"], strokes:16, jlpt:"N2" },
  { char:"構", meaning:"struktur / membangun", onyomi:["こう"], kunyomi:["かま"], strokes:14, jlpt:"N2" },
  { char:"造", meaning:"membuat / membangun", onyomi:["ぞう"], kunyomi:["つく"], strokes:10, jlpt:"N2" },
  { char:"製", meaning:"membuat / produk", onyomi:["せい"], kunyomi:[], strokes:14, jlpt:"N2" },
  { char:"品", meaning:"produk / kualitas", onyomi:["ひん","ぽん"], kunyomi:["しな"], strokes:9, jlpt:"N2" },
  { char:"器", meaning:"wadah / peralatan", onyomi:["き"], kunyomi:["うつわ"], strokes:15, jlpt:"N2" },
  { char:"材", meaning:"bahan / materi", onyomi:["ざい"], kunyomi:[], strokes:7, jlpt:"N2" },
  { char:"資", meaning:"modal / sumber daya", onyomi:["し"], kunyomi:[], strokes:13, jlpt:"N2" },
  { char:"源", meaning:"sumber / asal", onyomi:["げん"], kunyomi:["みなもと"], strokes:13, jlpt:"N2" },
  { char:"液", meaning:"cairan", onyomi:["えき"], kunyomi:[], strokes:11, jlpt:"N2" },
  { char:"固", meaning:"padat / keras", onyomi:["こ"], kunyomi:["かた"], strokes:8, jlpt:"N2" },
  { char:"体", meaning:"tubuh / badan", onyomi:["たい","てい"], kunyomi:["からだ"], strokes:7, jlpt:"N2" },
  { char:"物", meaning:"benda / hal", onyomi:["ぶつ","もつ"], kunyomi:["もの"], strokes:8, jlpt:"N2" },
  { char:"質", meaning:"kualitas / zat", onyomi:["しつ","しち"], kunyomi:[], strokes:15, jlpt:"N2" },
  { char:"量", meaning:"jumlah / mengukur", onyomi:["りょう"], kunyomi:["はか"], strokes:12, jlpt:"N2" },
  { char:"測", meaning:"mengukur", onyomi:["そく"], kunyomi:["はか"], strokes:12, jlpt:"N2" },

  // ══════════════════════════════════════════════════════════════════
  // N1 — representative kanji
  // ══════════════════════════════════════════════════════════════════
  { char:"覇", meaning:"dominasi / hegemoni", onyomi:["は"], kunyomi:[], strokes:19, jlpt:"N1" },
  { char:"威", meaning:"wibawa / kekuasaan", onyomi:["い"], kunyomi:["おど"], strokes:9, jlpt:"N1" },
  { char:"厳", meaning:"ketat / parah", onyomi:["げん","ごん"], kunyomi:["きび","おごそ"], strokes:17, jlpt:"N1" },
  { char:"峻", meaning:"curam / ketat", onyomi:["しゅん"], kunyomi:["けわ"], strokes:10, jlpt:"N1" },
  { char:"崇", meaning:"memuja / menghormati", onyomi:["すう"], kunyomi:["あが","たか"], strokes:11, jlpt:"N1" },
  { char:"煌", meaning:"berkilau / gemilang", onyomi:["こう"], kunyomi:["きらめ","きら"], strokes:13, jlpt:"N1" },
  { char:"彩", meaning:"warna / hiasan", onyomi:["さい"], kunyomi:["いろど"], strokes:11, jlpt:"N1" },
  { char:"誉", meaning:"kehormatan / kemuliaan", onyomi:["よ"], kunyomi:["ほま"], strokes:13, jlpt:"N1" },
  { char:"栄", meaning:"kemakmuran / kemuliaan", onyomi:["えい"], kunyomi:["さか","は"], strokes:9, jlpt:"N1" },
  { char:"華", meaning:"kemewahan / bunga", onyomi:["か","け"], kunyomi:["はな"], strokes:10, jlpt:"N1" },
  { char:"麗", meaning:"indah / cantik", onyomi:["れい"], kunyomi:["うるわ"], strokes:19, jlpt:"N1" },
  { char:"雅", meaning:"elegan / anggun", onyomi:["が"], kunyomi:["みや"], strokes:13, jlpt:"N1" },
  { char:"粋", meaning:"murni / stylish", onyomi:["すい"], kunyomi:["いき"], strokes:10, jlpt:"N1" },
  { char:"妙", meaning:"aneh / indah", onyomi:["みょう"], kunyomi:["たえ"], strokes:7, jlpt:"N1" },
  { char:"奇", meaning:"aneh / ganjil", onyomi:["き"], kunyomi:["くし"], strokes:8, jlpt:"N1" },
  { char:"稀", meaning:"langka / jarang", onyomi:["き","け"], kunyomi:["まれ"], strokes:12, jlpt:"N1" },
  { char:"稀", meaning:"langka", onyomi:["き"], kunyomi:["まれ"], strokes:12, jlpt:"N1" },
  { char:"曖", meaning:"ambigu / samar", onyomi:["あい"], kunyomi:[], strokes:17, jlpt:"N1" },
  { char:"昧", meaning:"gelap / samar", onyomi:["まい","ばい"], kunyomi:[], strokes:9, jlpt:"N1" },
  { char:"漠", meaning:"kabur / gurun", onyomi:["ばく"], kunyomi:[], strokes:13, jlpt:"N1" },
  { char:"茫", meaning:"luas / tak terbatas", onyomi:["ぼう","もう"], kunyomi:["ぼんやり"], strokes:9, jlpt:"N1" },
  { char:"虚", meaning:"kosong / palsu", onyomi:["きょ","こ"], kunyomi:["うつ","むな"], strokes:11, jlpt:"N1" },
  { char:"偽", meaning:"palsu / tiruan", onyomi:["ぎ"], kunyomi:["にせ","いつわ"], strokes:11, jlpt:"N1" },
  { char:"欺", meaning:"menipu / membohongi", onyomi:["ぎ"], kunyomi:["あざむ"], strokes:12, jlpt:"N1" },
  { char:"謀", meaning:"tipu daya / merencanakan", onyomi:["ぼう","む"], kunyomi:["はか"], strokes:16, jlpt:"N1" },
  { char:"略", meaning:"strategi / singkatan", onyomi:["りゃく"], kunyomi:[], strokes:11, jlpt:"N1" },
  { char:"策", meaning:"rencana / strategi", onyomi:["さく"], kunyomi:[], strokes:12, jlpt:"N1" },
  { char:"術", meaning:"seni / teknik", onyomi:["じゅつ"], kunyomi:[], strokes:11, jlpt:"N1" },
  { char:"懐", meaning:"kerinduan / memeluk", onyomi:["かい"], kunyomi:["ふところ","なつ"], strokes:16, jlpt:"N1" },
  { char:"憧", meaning:"merindukan / menginginkan", onyomi:["どう","しょう"], kunyomi:["あこが"], strokes:15, jlpt:"N1" },
  { char:"慕", meaning:"merindukan / mencintai", onyomi:["ぼ"], kunyomi:["した"], strokes:14, jlpt:"N1" },
  { char:"恋", meaning:"jatuh cinta", onyomi:["れん"], kunyomi:["こい","こい"], strokes:10, jlpt:"N1" },
  { char:"愛", meaning:"cinta / kasih", onyomi:["あい"], kunyomi:[], strokes:13, jlpt:"N1" },
  { char:"情", meaning:"perasaan / kondisi", onyomi:["じょう","せい"], kunyomi:["なさ"], strokes:11, jlpt:"N1" },
  { char:"涙", meaning:"air mata", onyomi:["るい"], kunyomi:["なみだ"], strokes:10, jlpt:"N1" },
  { char:"嘆", meaning:"mengeluh / takjub", onyomi:["たん"], kunyomi:["なげ"], strokes:14, jlpt:"N1" },
  { char:"嗚", meaning:"isak tangis", onyomi:["お","あ"], kunyomi:[], strokes:13, jlpt:"N1" },
  { char:"憤", meaning:"kemarahan / murka", onyomi:["ふん"], kunyomi:["いきどお"], strokes:15, jlpt:"N1" },
  { char:"怒", meaning:"marah", onyomi:["ど","と"], kunyomi:["おこ","いか"], strokes:9, jlpt:"N1" },
  { char:"憎", meaning:"membenci", onyomi:["ぞう"], kunyomi:["にく"], strokes:14, jlpt:"N1" },
  { char:"恨", meaning:"benci / dendam", onyomi:["こん"], kunyomi:["うら"], strokes:9, jlpt:"N1" },
  { char:"悔", meaning:"menyesal", onyomi:["かい"], kunyomi:["く","くや"], strokes:9, jlpt:"N1" },
  { char:"惜", meaning:"sayang / menyesal", onyomi:["せき"], kunyomi:["お","おし"], strokes:11, jlpt:"N1" },
  { char:"羨", meaning:"iri / cemburu", onyomi:["せん"], kunyomi:["うらや"], strokes:13, jlpt:"N1" },
  { char:"妬", meaning:"cemburu", onyomi:["と"], kunyomi:["ねた"], strokes:8, jlpt:"N1" },
  { char:"驚", meaning:"kaget / terkejut", onyomi:["きょう"], kunyomi:["おどろ"], strokes:22, jlpt:"N1" },
  { char:"恐", meaning:"takut / menakutkan", onyomi:["きょう"], kunyomi:["こわ","おそ"], strokes:10, jlpt:"N1" },
  { char:"慄", meaning:"gemetar / menggigil", onyomi:["りつ"], kunyomi:["おのの","ふる"], strokes:13, jlpt:"N1" },
  { char:"震", meaning:"gempa / gemetar", onyomi:["しん"], kunyomi:["ふる"], strokes:15, jlpt:"N1" },
  { char:"揺", meaning:"goyang / guncangan", onyomi:["よう"], kunyomi:["ゆ"], strokes:12, jlpt:"N1" },
];

export const kanjiByLevel = (level: string) =>
  kanjiData.filter((k) => k.jlpt === level);

export const kanjiCountByLevel: Record<string, number> = {
  N5: 80,
  N4: 166,
  N3: 367,
  N2: 367,
  N1: 1017,
};
